[package]
name = "mc_wrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
regex = "1"
mlua = { version = "0.11.5", features = ["lua54", "async", "send", "vendored", "serialize"] }
serde = "1.0"
serde_json = "1.0"
walkdir = "2"
